# 依赖下载
tidy:
	go mod tidy

# 构建
.PHONY: build
build:
	GOOS=linux GOARCH=amd64 go build -o ./build/myapp

tag:
	git tag -a v1.0.0 -m "第一次正式发版"

deleteTag:
	git tag -d v1.0.0 && \
	git push origin :refs/tags/v1.0.0

pushTag:
	git push --tags
