# =====================================================================
# 运行环境变量
# =====================================================================
env:
  # "prod"
  # "test"
  "dev"

# =====================================================================
# 服务器配置
# =====================================================================
server:
  http:
    # 端口
    port: 8080
    #
    router_prefix: "/"

# =====================================================================
# 数据库配置
# =====================================================================
db:
  # db类型 mysql | postgresql
  db_type: "mysql"
  # mysql配置
  mysql:
    # 地址
    addr: "8.136.109.181:33066"
    # 附加配置
    config: "charset=utf8mb4&parseTime=True&loc=Local"
    # 架构
    db_schema: "work"
    # 用户
    username: "admin"
    # 密码
    password: "123456"
    # 连接池配置
    pool:
      # 最大空闲连接数
      max_idle_conn: 5
      # 最大打开链接
      max_open_conn: 20
      # 最大空闲时间
      conn_max_idle_time: "30m"
      # 最大连接寿命
      conn_max_lifetime: "2h"
